[package]
name = "bh-mod"
version = "1.0.0"
edition = { workspace = true }
publish = false

[dependencies]
anyhow = "1.0.98"
clap = { workspace = true, features = ["cargo", "wrap_help"] }
clap-verbosity-flag = { version = "3.0.4", default-features = false, features = ["tracing"] }
humantime = "2.3.0"
indicatif = "0.18.4"
luwen = { workspace = true }
luwen-api = { workspace = true }
miette = { version = "5", features = ["fancy"] }
serde_json = { workspace = true }
tabled = "0.17.0"
terminal_size = "0.4.4"
thiserror = { workspace = true }
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["env-filter", "fmt", "registry"] }
