use num_derive::FromPrimitive;

#[derive(FromPrimitive)]
#[repr(u32)]
pub enum TelemetryTags {
    BoardIdHigh = 1,
    BoardIdLow = 2,
    AsicId = 3,
    HarvestingState = 4,
    UpdateTelemSpeed = 5,
    VCORE = 6,
    TDP = 7,
    TDC = 8,
    VddLimits = 9,
    ThmLimits = 10,
    AsicTemperature = 11,
    VregTemperature = 12,
    BoardTemperature = 13,
    AICLK = 14,
    AXICLK = 15,
    ARCCLK = 16,
    L2CPUCLK0 = 17,
    L2CPUCLK1 = 18,
    L2CPUCLK2 = 19,
    L2CPUCLK3 = 20,
    EthLiveStatus = 21,
    DdrStatus = 22,
    DdrSpeed = 23,
    EthFwVersion = 24,
    DdrFwVersion = 25,
    BmAppFwVersion = 26,
    BmBlFwVersion = 27,
    FlashBundleVersion = 28,
    CmFwVersion = 29,
    L2cpuFwVersion = 30,
    FanSpeed = 31,
    TimerHeartbeat = 32,
    TelemEnumCount = 33,
}
